from __future__ import annotations

KEYWORDS = {
    "Generic": {
        "Courage",
        "Destined",
        "Duty",
        "Expendable",
        "Experienced",
        "Experienced 2",
        "Experienced 3",
        "Experienced 4",
        "Fudo",
        "Gaijin",
        "Honor",
        "Imperial",
        "Inexperienced",
        "Jade",
        "Kharmic",
        "Kolat",
        "Ninja",
        "Nonhuman",
        "Oni",
        "Renew",
        "Sincerity",
        "Shadowlands",
        "Unique",
        "Void",
        "Winter",
    },
    "Holding": {
        "Barracks",
        "Castle",
        "Court",
        "Dojo",
        "Experienced 2",
        "Farm",
        "Forest",
        "Fortification",
        "Gambling House",
        "Geisha House",
        "Legacy",
        "Library",
        "Market",
        "Merchant Caravan",
        "Mine",
        "Pearl",
        "Pearl Bed",
        "Port",
        "Retainer",
        "Ruin",
        "Sake House",
        "Stables",
        "Stronghold",
        "Temple",
        "Village",
    },
    "Item": {
        "Knife",
        "Standard",
        "Naga",
        "Polearm",
        "Peasant",
        "Heavy Weapon",
        "Obsidian",
        "Axe",
        "Two-Handed",
        "Weapon",
        "Sword",
        "Chain",
        "Cursed",
        "Firearm",
        "One-Handed",
        "Gaijin",
        "Bow",
        "Skull",
        "Armor",
        "Scroll",
    },
    "Strategy": {
        "Kata",
        "Formation",
        "Edict",
    },
}
